
gt_auth_login:
    pattern:  /login
    defaults: { _controller: GTAuthBundle::Auth:login }

gt_auth_logout:
    pattern:  /logout
    defaults: { _controller: GTAuthBundle::Auth:logout }

gt_auth_login_check:
    pattern:   /login_check

